return {
  -- "williamboman/mason.nvim",
  -- dependencies = {
  --   "williamboman/mason-lspconfig.nvim",
  --   "WhoIsSethDaniel/mason-tool-installer.nvim",
  --   { 'j-hui/fidget.nvim', opts = {} }
  -- },
  -- config = function()
  --   local mason = require("mason")
  --   local mason_lspconfig = require("mason-lspconfig")
  --   local mason_tool_installer = require("mason-tool-installer")
  --
  --   mason.setup({
  --     ui = {
  --       icons = {
  --         package_installed = "✓",
  --         package_pending = "➜",
  --         package_uninstalled = "✗"
  --       }
  --     }
  --   })
  --
  --   mason_lspconfig.setup({
  --     ensure_installed = {
  --       "cssls",
  --       "dockerls",
  --       "docker_compose_language_service",
  --       "gopls",
  --       "html",
  --       "lua_ls",
  --       "prismals",
  --       "pyright",
  --       "tsserver",
  --     },
  --   })
  -- end
}
