import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 8
padding.y = 8
decorations = "Buttonless"
startup_mode = "Fullscreen"

# opacity = 0.8
# blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 14

offset.x = 1
offset.y = 10
